import { Plus } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { PageHeader } from '../components/PageHeader';
import { Panel } from '../components/Panel';
import { StatusBadge } from '../components/StatusBadge';
import { ScrollableTableFrame } from '../components/ScrollableTableFrame';
import { usePlatform } from '../platform/PlatformContext';

export function ClientManagementPage() {
  const navigate = useNavigate();
  const { state, selectClient } = usePlatform();
  return <div className="space-y-6"><PageHeader eyebrow="Super Admin" title="Client Administration" description="Create, inspect, and enter client context with currency, application, module, user, and audit linkage." /><Panel title="Clients" description="All platform clients and subscription states." action={<button className="form-button-primary inline-flex items-center gap-2" onClick={() => navigate('/admin/clients/create')}><Plus className="h-4 w-4" />Create Client</button>}><ScrollableTableFrame count={state.clients.length}><table className="min-w-[1180px] w-full text-sm"><thead><tr className="border-b border-white/10 text-left text-xs uppercase tracking-[0.1em] text-slate-500">{['Client ID','Client Name','Region','Market','Currency','Applications','Enabled Modules','Disabled Modules','Status','Created','Actions'].map((item) => <th key={item} className="px-3 py-3">{item}</th>)}</tr></thead><tbody>{state.clients.map((client) => <tr key={client.clientId} className="border-b border-white/10 hover:bg-white/[0.04]"><td className="px-3 py-3 text-cyan-200">{client.clientId}</td><td className="px-3 py-3 font-medium text-white">{client.clientName}</td><td className="px-3 py-3">{client.region}</td><td className="px-3 py-3">{client.market}</td><td className="px-3 py-3">{client.currency}</td><td className="px-3 py-3 text-cyan-200">{client.enabledApplications.length}</td><td className="px-3 py-3 text-emerald-200">{client.enabledModules.length}</td><td className="px-3 py-3 text-rose-200">{client.disabledModules.length}</td><td className="px-3 py-3"><StatusBadge status={client.status} /></td><td className="px-3 py-3">{client.createdDate}</td><td className="px-3 py-3"><div className="flex gap-2"><button className="form-button-subtle py-1 text-xs" onClick={() => navigate(`/admin/clients/${client.clientId}/edit`)}>Edit</button><button className="form-button-subtle py-1 text-xs" onClick={() => navigate(`/admin/clients/${client.clientId}/health`)}>Health</button><button className="form-button-primary py-1 text-xs" onClick={() => { selectClient(client.clientId); navigate('/'); }}>Open</button></div></td></tr>)}</tbody></table></ScrollableTableFrame></Panel></div>;
}
