import { FormEvent, useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { PageHeader } from '../components/PageHeader';
import { Panel } from '../components/Panel';
import { platformRoles } from '../platform/data';
import { usePlatform } from '../platform/PlatformContext';

export function CreateUserPage() {
  const navigate = useNavigate(); const { state, selectedClient, canSelectPlatform, createUser } = usePlatform(); const initialClient = selectedClient ?? state.clients[0];
  const [form, setForm] = useState({ firstName: '', lastName: '', loginName: '', email: '', clientId: initialClient.clientId, region: initialClient.region, market: initialClient.market, roles: ['Viewer'], assignedApplications: [...initialClient.enabledApplications], assignedModules: [...initialClient.enabledModules], status: 'Active' as const });
  const client = state.clients.find((item) => item.clientId === form.clientId) ?? initialClient;
  const roleOptions = platformRoles.filter((role) => role !== 'Super Admin');
  const clientOptions = canSelectPlatform ? state.clients : state.clients.filter((item) => item.clientId === initialClient.clientId);
  const fullName = `${form.firstName} ${form.lastName}`.trim();
  function selectClient(clientId: string) { const next = state.clients.find((item) => item.clientId === clientId)!; setForm((current) => ({ ...current, clientId, region: next.region, market: next.market, assignedApplications: next.enabledApplications, assignedModules: next.enabledModules, roles: current.roles.includes('Super Admin') ? ['Company Admin'] : current.roles })); }
  function toggle(field: 'roles' | 'assignedApplications' | 'assignedModules', value: string) { setForm((current) => ({ ...current, [field]: current[field].includes(value) ? current[field].filter((item) => item !== value) : [...current[field], value] })); }
  function submit(event: FormEvent) { event.preventDefault(); createUser(form); navigate('/admin/users'); }
  const invalidModules = useMemo(() => form.assignedModules.filter((module) => client.disabledModules.includes(module)), [form.assignedModules, client.disabledModules]);
  return <div className="space-y-6"><PageHeader eyebrow="User Management" title="Create User" description="User ID and full name are generated automatically. Assignments are limited to modules enabled for the selected client." /><Panel title="User profile and access" description={`Generated full name: ${fullName || 'First Name + Last Name'}`}><form className="space-y-5" onSubmit={submit}><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3"><Field label="First Name" value={form.firstName} onChange={(value) => setForm({ ...form, firstName: value })} /><Field label="Last Name" value={form.lastName} onChange={(value) => setForm({ ...form, lastName: value })} /><Field label="Login Name" value={form.loginName} onChange={(value) => setForm({ ...form, loginName: value })} /><Field label="Email ID" type="email" value={form.email} onChange={(value) => setForm({ ...form, email: value })} /><label className="text-sm text-slate-300">Client<select className="form-input mt-1 w-full" value={form.clientId} onChange={(event) => selectClient(event.target.value)} disabled={!canSelectPlatform}>{clientOptions.map((item) => <option key={item.clientId} value={item.clientId}>{item.clientName}</option>)}</select></label><Field label="Region" value={form.region} readOnly onChange={() => undefined} /><Field label="Market" value={form.market} readOnly onChange={() => undefined} /></div><ChoiceGrid title="Roles" values={roleOptions} selected={form.roles} onToggle={(value) => toggle('roles', value)} /><ChoiceGrid title="Assigned Applications" values={client.enabledApplications} selected={form.assignedApplications} onToggle={(value) => toggle('assignedApplications', value)} /><ChoiceGrid title="Assigned Modules" values={client.enabledModules} selected={form.assignedModules} onToggle={(value) => toggle('assignedModules', value)} />{invalidModules.length ? <p className="rounded-xl border border-rose-300/20 bg-rose-400/10 p-3 text-sm text-rose-100">Disabled modules cannot be assigned: {invalidModules.join(', ')}</p> : null}<div className="flex justify-end gap-3"><button type="button" className="form-button-subtle" onClick={() => navigate('/admin/users')}>Cancel</button><button className="form-button-primary" disabled={Boolean(invalidModules.length)}>Create User</button></div></form></Panel></div>;
}

function Field({ label, value, onChange, type = 'text', readOnly = false }: { label: string; value: string; onChange: (value: string) => void; type?: string; readOnly?: boolean }) { return <label className="text-sm text-slate-300">{label}<input className="form-input mt-1 w-full" type={type} value={value} onChange={(event) => onChange(event.target.value)} readOnly={readOnly} required={!readOnly} /></label>; }
function ChoiceGrid({ title, values, selected, onToggle }: { title: string; values: string[]; selected: string[]; onToggle: (value: string) => void }) { return <fieldset><legend className="mb-3 text-sm font-semibold text-white">{title}</legend><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{values.map((value) => <label key={value} className="flex items-center gap-3 rounded-xl border border-white/10 bg-slate-950/30 p-3 text-sm text-slate-200"><input type="checkbox" checked={selected.includes(value)} onChange={() => onToggle(value)} />{value}</label>)}</div></fieldset>; }
