import { FormEvent, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { PageHeader } from '../components/PageHeader';
import { Panel } from '../components/Panel';
import { platformApplications, platformModules } from '../platform/data';
import { usePlatform } from '../platform/PlatformContext';
import type { ClientStatus, CurrencyCode } from '../platform/types';

const markets = [{ market: 'United States', region: 'North America', currency: 'USD' }, { market: 'India', region: 'Asia', currency: 'INR' }, { market: 'European Union', region: 'Europe', currency: 'EUR' }, { market: 'United Kingdom', region: 'Europe', currency: 'GBP' }, { market: 'United Arab Emirates', region: 'Middle East', currency: 'AED' }] as const;

export function CreateClientPage() {
  const navigate = useNavigate(); const { createClient } = usePlatform();
  const [form, setForm] = useState({ clientName: '', market: 'United States', region: 'North America', currency: 'USD' as CurrencyCode, status: 'Trial' as ClientStatus, enabledApplications: platformApplications.filter((item) => item !== 'Platform Management'), enabledModules: platformModules.filter((item) => item !== 'Admin') });
  function submit(event: FormEvent) { event.preventDefault(); const client = createClient(form); navigate(`/admin/clients/${client.clientId}/health`); }
  function toggle(field: 'enabledApplications' | 'enabledModules', value: string) { setForm((current) => ({ ...current, [field]: current[field].includes(value) ? current[field].filter((item) => item !== value) : [...current[field], value] })); }
  return <div className="space-y-6"><PageHeader eyebrow="Client Administration" title="Create Client" description="Client ID, created date, module access, currency, and audit linkage are generated automatically." /><Panel title="Client profile" description="Commercial and access configuration for the new tenant."><form className="space-y-5" onSubmit={submit}><div className="grid gap-4 md:grid-cols-2"><label className="text-sm text-slate-300">Client Name<input className="form-input mt-1 w-full" value={form.clientName} onChange={(event) => setForm({ ...form, clientName: event.target.value })} required /></label><label className="text-sm text-slate-300">Market<select className="form-input mt-1 w-full" value={form.market} onChange={(event) => { const item = markets.find((market) => market.market === event.target.value)!; setForm({ ...form, market: item.market, region: item.region, currency: item.currency }); }}>{markets.map((item) => <option key={item.market}>{item.market}</option>)}</select></label><label className="text-sm text-slate-300">Region<input className="form-input mt-1 w-full" value={form.region} readOnly /></label><label className="text-sm text-slate-300">Currency<input className="form-input mt-1 w-full" value={form.currency} readOnly /></label><label className="text-sm text-slate-300">Status<select className="form-input mt-1 w-full" value={form.status} onChange={(event) => setForm({ ...form, status: event.target.value as ClientStatus })}><option>Active</option><option>Trial</option><option>Suspended</option></select></label></div><AssignmentGrid title="Enabled Applications" values={platformApplications.filter((item) => item !== 'Platform Management')} selected={form.enabledApplications} onToggle={(value) => toggle('enabledApplications', value)} /><AssignmentGrid title="Enabled Modules" values={platformModules.filter((item) => item !== 'Admin')} selected={form.enabledModules} onToggle={(value) => toggle('enabledModules', value)} /><div className="flex justify-end gap-3"><button type="button" className="form-button-subtle" onClick={() => navigate('/admin/clients')}>Cancel</button><button className="form-button-primary">Create Client</button></div></form></Panel></div>;
}

function AssignmentGrid({ title, values, selected, onToggle }: { title: string; values: string[]; selected: string[]; onToggle: (value: string) => void }) { return <fieldset><legend className="mb-3 text-sm font-semibold text-white">{title}</legend><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{values.map((value) => <label key={value} className="flex items-center gap-3 rounded-xl border border-white/10 bg-slate-950/30 p-3 text-sm text-slate-200"><input type="checkbox" checked={selected.includes(value)} onChange={() => onToggle(value)} />{value}</label>)}</div></fieldset>; }
