import { PageHeader } from '../components/PageHeader';
import { Panel } from '../components/Panel';
import { StatusBadge } from '../components/StatusBadge';
import { usePlatform } from '../platform/PlatformContext';

export function PlatformWidgetsPage() {
  const { state, updateWidget, resetWidgets } = usePlatform();
  const widgets = [...state.widgets].sort((a, b) => a.displayOrder - b.displayOrder);
  return <div className="space-y-6"><PageHeader eyebrow="Platform Configuration" title="Configurable Widgets" description="Control platform widget visibility and display order without changing client operational data." /><Panel title="Widget register" description="Show, hide, reorder, or restore platform defaults." action={<button className="form-button-subtle" onClick={resetWidgets}>Reset to Default</button>}><div className="overflow-x-auto"><table className="min-w-[980px] w-full text-sm"><thead><tr className="border-b border-white/10 text-left text-xs uppercase tracking-[0.1em] text-slate-500">{['Widget ID','Widget Name','Module','Owner','Clients','Status','Visible','Order','Actions'].map((item) => <th key={item} className="px-3 py-3">{item}</th>)}</tr></thead><tbody>{widgets.map((widget) => <tr key={widget.widgetId} className="border-b border-white/10"><td className="px-3 py-3 text-cyan-200">{widget.widgetId}</td><td className="px-3 py-3 font-medium text-white">{widget.widgetName}</td><td className="px-3 py-3">{widget.moduleName}</td><td className="px-3 py-3">{widget.owner}</td><td className="px-3 py-3">{widget.clientCount}</td><td className="px-3 py-3"><StatusBadge status={widget.status} /></td><td className="px-3 py-3"><StatusBadge status={widget.visible ? 'Visible' : 'Hidden'} /></td><td className="px-3 py-3">{widget.displayOrder}</td><td className="px-3 py-3"><div className="flex gap-2"><button className="form-button-subtle py-1 text-xs" onClick={() => updateWidget(widget.widgetId, { visible: !widget.visible })}>{widget.visible ? 'Hide' : 'Show'}</button><button className="form-button-subtle px-2 py-1 text-xs" onClick={() => updateWidget(widget.widgetId, { displayOrder: Math.max(1, widget.displayOrder - 1) })}>↑</button><button className="form-button-subtle px-2 py-1 text-xs" onClick={() => updateWidget(widget.widgetId, { displayOrder: widget.displayOrder + 1 })}>↓</button></div></td></tr>)}</tbody></table></div></Panel></div>;
}
